return {
    azure_pipelines_ls = require("plugins.lsp.servers.azure_pipelines_ls"),
    bashls = {},
    basedpyright = require("plugins.lsp.servers.basedPyright"),
    clangd = require("plugins.lsp.servers.clangd"),
    cssls = require("plugins.lsp.servers.cssls"),
    cssmodules_ls = {},
    dockerls = {},
    jsonls = {},
    lua_ls = require("plugins.lsp.servers.lua_ls"),
    marksman = {},
    rust_analyzer = require("plugins.lsp.servers.rust_analyzer"),
    tsserver = require("plugins.lsp.servers.tsserver"),
    -- yamlls = require("plugins.lsp.servers.yamlls"),
}
