local key = vim.keymap.set

key({ "n", "v", "o" }, "H", "^", { desc = "End of line" })
key({ "n", "v", "o" }, "L", "$", { desc = "Start of line" })
key("n", "<c-h>", "<c-w>h", { desc = "Go to Left Window" })
key("n", "<c-j>", "<c-w>j", { desc = "Go to Lower Window" })
key("n", "<c-k>", "<c-w>k", { desc = "Go to Upper Window" })
key("n", "<c-l>", "<c-w>l", { desc = "Go to Right Window" })
key("n", "<m-down>", "<c-w>-", { desc = "Decrease height" })
key("n", "<m-up>", "<c-w>+", { desc = "Increase height" })
key("n", "<m-right>", "<c-w>>", { desc = "Increase width" })
key("n", "<m-left>", "<c-w><", { desc = "Decrease width" })
key("n", "<m-J>", "<c-w>=", { desc = "Equal height" })
key("n", "<m-K>", "<c-w>_", { desc = "Max height" })
key("n", "<m-L>", "<c-w>|", { desc = "Max width" })
key("t", "<esc>", "<c-\\><c-n>", {})
key({ "n", "v", "o" }, "<leader>y", '"+y', { desc = "Yank to system" })
key({ "n", "v", "o" }, "<leader>p", '"+p', { desc = "Paste from system" })
key("n", "<leader>H", "<cmd>nohl<CR>", { desc = "Clear highlighting" })
key("n", "j", [[(v:count > 1 ? 'm`' . v:count : 'g') . 'j']], { expr = true })
key("n", "k", [[(v:count > 1 ? 'm`' . v:count : 'g') . 'k']], { expr = true })
key("n", "<C-d>", function()
    vim.cmd([[execute "normal! \<C-d>zz"]])
end, { desc = "Scroll downwards" })
key("n", "<C-u>", function()
    vim.cmd([[execute "normal! \<C-u>zz"]])
end, { desc = "Scroll upwards" })
key("n", "n", function()
    pcall(vim.cmd, "normal! n")
    vim.cmd("normal! zzzv")
end, { desc = "Next result" })
key("n", "N", function()
    pcall(vim.cmd, "normal! N")
    vim.cmd("normal! zzzv")
end, { desc = "Previous result" })
key("v", "<", "<gv")
key("v", ">", ">gv")

-- Toggles
key("n", "<leader>us", "<cmd>setlocal spell!<cr>", { desc = "Toggle Spelling" })
key("n", "<leader>uw", "<cmd>setlocal wrap!<cr>", { desc = "Toggle Wrap" })
key("n", "<leader>uL", "<cmd>setlocal relativenumber!<cr>", { desc = "Toggle Relative Number" })
key("n", "<leader>ul", "<cmd>setlocal number!<cr>", { desc = "Toggle Line Number" })
key("n", "<leader>ud", function()
    local enabled = vim.diagnostic.is_enabled()
    vim.diagnostic.enable(not enabled)
end, { desc = "Toggle Diagnostics" })
key("n", "<leader>uh", function()
    vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled())
end, { desc = "Toggle Inlay Hints" })
key("n", "<leader>uc", function()
    local cl = vim.o.conceallevel
    vim.o.conceallevel = cl > 0 and 0 or 2
end, { desc = "Toggle Conceal" })
key("n", "<leader>uv", "<cmd>setlocal list!<cr>", { desc = "Toggle List Chars" })
key("n", "<leader>ub", function()
    vim.o.background = vim.o.background == "dark" and "light" or "dark"
end, { desc = "Toggle Background" })
key("n", "<leader>uG", function()
    require("gitsigns").toggle_current_line_blame()
end, { desc = "Toggle Git Blame" })
key("n", "<leader>uW", function()
    require("gitsigns").toggle_word_diff()
end, { desc = "Toggle Git Word Diff" })
key("n", "<leader>uH", function()
    require("gitsigns").toggle_linehl()
end, { desc = "Toggle Git Line Highlight" })
key("n", "<leader>un", function()
    require("gitsigns").toggle_numhl()
end, { desc = "Toggle Git Num Highlight" })
key("n", "<leader>uX", function()
    require("gitsigns").toggle_signs()
end, { desc = "Toggle Git Signs" })
