local opts = {
    ensure_installed = {
        "asm",
        "awk",
        "bash",
        "c",
        "c3",
        "cmake",
        "comment",
        "cpp",
        "css",
        "csv",
        "cuda",
        "diff",
        "dockerfile",
        "dot",
        "doxygen",
        "dtd",
        "editorconfig",
        "fsh",
        "gdscript",
        "gdshader",
        "git_config",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "glsl",
        "haskell",
        "haskell_persistent",
        "hlsl",
        "html",
        "html_tags",
        "http",
        "idl",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "just",
        "latex",
        "lua",
        "luadoc",
        "luap",
        "luau",
        "make",
        "markdown",
        "markdown_inline",
        "matlab",
        "mermaid",
        "ninja",
        "odin",
        "powershell",
        "printf",
        "proto",
        "python",
        "query",
        "regex",
        "requirements",
        "rust",
        "scss",
        "ssh_config",
        "starlark",
        "svelte",
        "tmux",
        "toml",
        "tsx",
        "tsv",
        "typescript",
        "typst",
        "vim",
        "vimdoc",
        "vue",
        "xml",
        "yaml",
        "zig",
    },
    filetypes = {
        "bash",
        "bzl",
        "c",
        "c3",
        "checkhealth",
        "cmake",
        "cmakecache",
        "cpp",
        "css",
        "csv",
        "cterm",
        "diff",
        "dockerfile",
        "dot",
        "doxygen",
        "editorconfig",
        "fish",
        "gdb",
        "gdscript",
        "gdshader",
        "gitattributes",
        "gitcommit",
        "gitconfig",
        "gitignore",
        "gitolite",
        "gitrebase",
        "gitsendemail",
        "glsl",
        "haskell",
        "html",
        "javascript",
        "jsdoc",
        "lua",
        "printf",
        "regex",
        "vimdoc",
        "typescript",
        "help",
        "idl",
        "json",
        "json5",
        "jsonnet",
        "ld",
        "less",
        "lhaskell",
        "lsp_markdown",
        "make",
        "man",
        "manual",
        "markdown",
        "mermaid",
        "messages",
        "ninja",
        "obj",
        "objc",
        "objcpp",
        "objdump",
        "odin",
        "pandoc",
        "pdf",
        "proto",
        "python",
        "python2",
        "requirements",
        "rust",
        "sed",
        "sh",
        "shada",
        "shaderslang",
        "sshconfig",
        "sshdconfig",
        "stylus",
        "systemd",
        "tmux",
        "toml",
        "valgrind",
        "vim",
        "viminfo",
        "vimnormal",
        "wget",
        "wget2",
        "whitespace",
        "winbatch",
        "xml",
        "yacc",
        "yaml",
        "zig",
    },
}

local already_installed = require("nvim-treesitter").get_installed()
local parsers_to_install = vim.iter(opts.ensure_installed)
    :filter(function(parser)
        return not vim.tbl_contains(already_installed, parser)
    end)
    :totable()
require("nvim-treesitter").install(parsers_to_install)
require("nvim-treesitter").update(already_installed)
require("treesitter-context").setup({
    max_lines = 3,
    multiline_threshold = 1,
    min_window_height = 20,
})

vim.keymap.set("n", "[c", function()
    vim.schedule(function()
        require("treesitter-context").go_to_context()
    end)
    return "<Ignore>"
end, { desc = "Jump to upper context", expr = true })

vim.api.nvim_create_autocmd("FileType", {
    pattern = opts.filetypes,
    callback = function()
        vim.treesitter.start()
        vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
        vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
    end,
})
