local ensure_installed = {
    "asm",
    "awk",
    "bash",
    "c",
    "c3",
    "cmake",
    "comment",
    "cpp",
    "css",
    "csv",
    "cuda",
    "diff",
    "dockerfile",
    "dot",
    "doxygen",
    "dtd",
    "editorconfig",
    "fsh",
    "gdscript",
    "gdshader",
    "git_config",
    "git_rebase",
    "gitattributes",
    "gitcommit",
    "gitignore",
    "glsl",
    "haskell",
    "haskell_persistent",
    "hlsl",
    "html",
    "html_tags",
    "http",
    "idl",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "just",
    "latex",
    "lua",
    "luadoc",
    "luap",
    "luau",
    "make",
    "markdown",
    "markdown_inline",
    "matlab",
    "mermaid",
    "ninja",
    "odin",
    "powershell",
    "printf",
    "proto",
    "python",
    "query",
    "regex",
    "requirements",
    "rust",
    "scss",
    "ssh_config",
    "starlark",
    "svelte",
    "tmux",
    "toml",
    "tsx",
    "tsv",
    "typescript",
    "typst",
    "vim",
    "vimdoc",
    "vue",
    "xml",
    "yaml",
    "zig",
}
local filetypes = {
    "bash",
    "bzl",
    "c",
    "c3",
    "checkhealth",
    "cmake",
    "cmakecache",
    "cpp",
    "css",
    "csv",
    "cterm",
    "diff",
    "dockerfile",
    "dot",
    "doxygen",
    "editorconfig",
    "fish",
    "gdb",
    "gdscript",
    "gdshader",
    "gitattributes",
    "gitcommit",
    "gitconfig",
    "gitignore",
    "gitolite",
    "gitrebase",
    "gitsendemail",
    "glsl",
    "haskell",
    "html",
    "javascript",
    "jsdoc",
    "lua",
    "printf",
    "regex",
    "vimdoc",
    "typescript",
    "help",
    "idl",
    "json",
    "json5",
    "jsonnet",
    "ld",
    "less",
    "lhaskell",
    "lsp_markdown",
    "make",
    "man",
    "manual",
    "markdown",
    "mermaid",
    "messages",
    "ninja",
    "obj",
    "objc",
    "objcpp",
    "objdump",
    "odin",
    "pandoc",
    "pdf",
    "proto",
    "python",
    "python2",
    "requirements",
    "rust",
    "sed",
    "sh",
    "shada",
    "shaderslang",
    "sshconfig",
    "sshdconfig",
    "stylus",
    "systemd",
    "tmux",
    "toml",
    "valgrind",
    "vim",
    "viminfo",
    "vimnormal",
    "wget",
    "wget2",
    "whitespace",
    "winbatch",
    "xml",
    "yacc",
    "yaml",
    "zig",
}

require("nvim-treesitter").install(ensure_installed)

local move = require("nvim-treesitter-textobjects.move")
local swap = require("nvim-treesitter-textobjects.swap")

local function goto_map(lhs, fn, query, desc)
    vim.keymap.set("n", lhs, function()
        fn(query)
    end, { desc = desc })
end

goto_map("]m", move.goto_next_start, "@function.outer", "Next function")
goto_map("]C", move.goto_next_start, "@class.outer", "Next class")
goto_map("]M", move.goto_next_end, "@function.outer", "Next function end")
goto_map("[m", move.goto_previous_start, "@function.outer", "Prev function")
goto_map("[C", move.goto_previous_start, "@class.outer", "Prev class")
goto_map("[M", move.goto_previous_end, "@function.outer", "Prev function end")

vim.keymap.set("n", "<leader>ap", function()
    swap.swap_next("@parameter.inner")
end, { desc = "Swap next parameter" })
vim.keymap.set("n", "<leader>aP", function()
    swap.swap_previous("@parameter.inner")
end, { desc = "Swap prev parameter" })

vim.api.nvim_create_autocmd("FileType", {
    pattern = filetypes,
    callback = function()
        vim.treesitter.start()
        vim.wo.foldexpr = "v:lua.vim.treesitter.foldexpr()"
        vim.bo.indentexpr = "v:lua.require'nvim-treesitter'.indentexpr()"
    end,
})
