return {
    misc = {
        dots = "󰇘",
        slash = "╱",
        minus = "",
        plus = "",
        clock = "󰥔  ",
        python = "",
    },
    separator = {
        full = {
            left = "",
            right = "",
        },
        line = {
            left = "",
            right = "",
        },
        bar = "┃",
    },
    dap = {
        Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
        Breakpoint = { " ", "DiagnosticError" },
        BreakpointCondition = " ",
        BreakpointRejected = { " ", "DiagnosticError" },
        LogPoint = "󰑃",
    },
    files = {
        modified = "",
        readonly = "",
        unnamed = "[No Name]",
        newfile = "[New]",
    },
    diagnostics = {
        Error = " ",
        Warn = " ",
        Hint = " ",
        Info = " ",
    },
    todo = {
        todo = "",
        hack = "",
        warn = "",
        perf = "",
        note = "",
        test = "⏲",
    },
    git = {
        added = "",
        modified = "",
        removed = "",
    },
    folder = {
        closed = "",
        open = "",
    },
    fold = {
        closed = "",
        open = "",
        separator = "│",
    },
    chevron = {
        right = "",
        left = "",
        down = "",
        up = "",
    },
    progress = {
        pending = "󰑓",
        done = "",
        offline = "",
    },
    kinds = {
        Array = " ",
        Boolean = "󰨙 ",
        Class = " ",
        Codeium = "󰘦 ",
        Color = " ",
        Control = " ",
        Collapsed = " ",
        Constant = "󰏿 ",
        Constructor = " ",
        Copilot = " ",
        Enum = " ",
        EnumMember = " ",
        Event = " ",
        Field = " ",
        File = " ",
        Folder = " ",
        Function = "󰊕 ",
        Interface = " ",
        Key = " ",
        Keyword = " ",
        Method = "󰊕 ",
        Module = " ",
        Namespace = "󰦮 ",
        Null = " ",
        Number = "󰎠 ",
        Object = " ",
        Operator = " ",
        Package = " ",
        Property = " ",
        Reference = " ",
        Snippet = " ",
        String = " ",
        Struct = "󰆼 ",
        TabNine = "󰏚 ",
        Text = " ",
        TypeParameter = " ",
        Unit = " ",
        Value = " ",
        Variable = "󰀫 ",
    },
}
