return {
	-- {
	-- 	"folke/edgy.nvim",
	-- 	dependencies = {
	-- 		"echasnovski/mini.animate",
	-- 	},
	-- 	event = "VeryLazy",
	-- 	keys = {
	-- 		{
	-- 			"<leader>ue",
	-- 			function()
	-- 				require("edgy").toggle()
	-- 			end,
	-- 			desc = "Edgy toggle Window",
	-- 		},
	-- 		{
	-- 			"<leader>uE",
	-- 			function()
	-- 				require("edgy").select()
	-- 			end,
	-- 			desc = "Edgy Select Window",
	-- 		},
	-- 	},
	-- 	opts = {
	-- 		wo = {
	-- 			winbar = false,
	-- 		},
	-- 		bottom = {
	-- 			"Trouble",
	-- 			{
	-- 				ft = "qf",
	-- 			},
	-- 			{
	-- 				ft = "help",
	-- 				size = { height = 20 },
	-- 				-- only show help buffers
	-- 				filter = function(buf)
	-- 					return vim.bo[buf].buftype == "help"
	-- 				end,
	-- 			},
	-- 			{
	-- 				ft = "spectre_panel",
	-- 				open = function()
	-- 					require("spectre").open()
	-- 				end,
	-- 				size = { height = 24, width = 80 },
	-- 			},
	-- 			{
	-- 				ft = "oil",
	-- 				pinned = true,
	-- 				open = function()
	-- 					require("oil").open(vim.loop.cwd())
	-- 				end,
	-- 				size = { height = 30, width = 30 },
	-- 			},
	-- 			"dapui_console",
	-- 			"dap-repl",
	-- 		},
	-- 		left = {
	-- 			{
	-- 				ft = "neo-tree",
	-- 				filter = function(buf)
	-- 					return vim.b[buf].neo_tree_source == "filesystem"
	-- 				end,
	-- 				size = { height = 0.5 },
	-- 			},
	-- 			{
	-- 				ft = "neo-tree",
	-- 				filter = function(buf)
	-- 					return vim.b[buf].neo_tree_source == "git_status"
	-- 				end,
	-- 				open = "Neotree position=right git_status",
	-- 			},
	-- 			{
	-- 				ft = "neo-tree",
	-- 				filter = function(buf)
	-- 					return vim.b[buf].neo_tree_source == "buffers"
	-- 				end,
	-- 				open = "Neotree position=top buffers",
	-- 			},
	-- 			{
	-- 				ft = "Outline",
	-- 				open = "SymbolsOutline",
	-- 			},
	-- 			"dapui_scopes",
	-- 			"dapui_breakpoints",
	-- 			"dapui_stacks",
	-- 			"dapui_watches",
	-- 			"dapui_scopes",
	-- 		},
	-- 		right = {
	-- 			{
	-- 				ft = "gitrebase",
	-- 				size = {
	-- 					width = 100,
	-- 				},
	-- 			},
	-- 			{
	-- 				ft = "gitcommit",
	-- 				size = {
	-- 					width = 72,
	-- 				},
	-- 			},
	-- 			-- PERF: Toggleterm performs terribly with edgy.
	-- 			-- {
	-- 			-- 	ft = "toggleterm",
	-- 			-- 	size = {
	-- 			-- 		width = function()
	-- 			-- 			return 100 -- math.min(vim.o.columns * 0.25, 100)
	-- 			-- 		end,
	-- 			-- 	},
	-- 			-- 	filter = function(_, win)
	-- 			-- 		return vim.api.nvim_win_get_config(win).relative == ""
	-- 			-- 	end,
	-- 			-- },
	-- 		},
	-- 	},
	-- },
}
